<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net8.0-android;net8.0-ios;</TargetFrameworks>
        <OutputType Condition="'$(TargetFramework)' != 'net8.0'">Exe</OutputType>
        <RootNamespace>Weighter</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Display name -->
        <ApplicationTitle>Weighter</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>au.com.weighter</ApplicationId>
        <ApplicationIdGuid>103366FB-07D8-4AE8-8BE8-F91CB86A891E</ApplicationIdGuid>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*" />
        <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*" />

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncAwaitBestPractices" Version="7.0.0" />
        <PackageReference Include="CommunityToolkit.Common" Version="8.2.2" />
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.2.2" />
        <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.2" />
        <PackageReference Include="CommunityToolkit.Maui" Version="7.0.1" />
        <PackageReference Include="CommunityToolkit.Maui.Markup" Version="4.0.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
        <PackageReference Include="epj.RouteGenerator" Version="1.0.1" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0-preview.1.24080.9" />
        <PackageReference Include="Prism.DryIoc.Maui" Version="9.0.401-pre" />
        <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
        <PackageReference Include="sqlite-net-pcl" Version="1.9.141-beta" />
        <PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.8" />
        <PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" Version="2.1.8" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="WhiteCane" Version="1.0.3" />
    </ItemGroup>

    <!-- Android-->
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
        <GoogleServicesJson Include="**\Android\google-services.json" />
    </ItemGroup>

    <!-- Android -->
    <ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-android')) != true">
        <Compile Remove="**\Android\**\*.cs" />
        <None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>

    <!-- IOS-->
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
        <BundleResource Include="**\iOS\GoogleService-Info.plist" />
    </ItemGroup>

    <!-- IOS -->
    <ItemGroup Condition="$(TargetFramework.StartsWith('net8.0-ios')) != true">
        <Compile Remove="**\iOS\**\*.cs" />
        <None Include="**\iOS\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Update="Resources\Copy Registers\RegistrationRegister.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>RegistrationRegister.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\Copy Registers\InitRegister.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>InitRegister.resx</DependentUpon>
        </Compile>
        <Compile Update="Resources\Copy Registers\GlobalRegister.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>GlobalRegister.resx</DependentUpon>
        </Compile>
      <EmbeddedResource Update="Resources\Copy Registers\RegistrationRegister.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>RegistrationRegister.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Copy Registers\InitRegister.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>InitRegister.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Copy Registers\GlobalRegister.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>GlobalRegister.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
</Project>
